name: time_tracking
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_core:
    git:
      url: https://github.com/bemohansingh/flutter_core.git
      ref: main
  flutter_design_extension:
    git:
      url: https://github.com/bemohansingh/Flutter_Design_Extension
      ref: main
  flutter_module_architecture:
    git:
      url: https://github.com/bemohansingh/Flutter-Module-Architecture
      ref: main
  intl: ^0.17.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/languages/
